### ISSUE TITLE
Crash mempool.space/backend/dist/api/bisq/bisq.js:130

### ISSUE THREAD

**Issue by Emzy** [mempool/mempool#145]
### Description

I had a crash yesterday. It was stuck. Not existing to shell.
I had to crtl+c out of it and restart.

#### Version

v2.0-SNAPSHOT (55646b57) 

### Steps to reproduce

No idea.

### Screenshots
```
Fetched transaction 24 / 30
Fetched transaction 25 / 30
Fetched transaction 26 / 30
/home/user/mempool.space/backend/dist/api/bisq/bisq.js:130
            trades.forEach((trade) => {
                   ^

TypeError: trades.forEach is not a function
    at Request._callback (/home/emzy/mempool.space/backend/dist/api/bisq/bisq.js:130:20)
    at Request.self.callback (/home/emzy/mempool.space/backend/node_modules/request/request.js:185:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (/home/emzy/mempool.space/backend/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (/home/emzy/mempool.space/backend/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by wiz** [comment]
yeah we had the same crash yesterday and I reported it to simon privately, sorry to hear you had the same issue
