### ISSUE TITLE
WebSocket errors are not handled, permessage-deflate is not handled

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#157]
```
Nov 15 01:50:21 [76610] DEBUG: Mempool updated in 0.174 seconds
node:events:304
      throw er; // Unhandled 'error' event
      ^

RangeError: Invalid WebSocket frame: RSV1 must be clear
    at Receiver.getInfo (/mempool/mainnet/backend/node_modules/ws/lib/receiver.js:178:14)
    at Receiver.startLoop (/mempool/mainnet/backend/node_modules/ws/lib/receiver.js:131:22)
    at Receiver._write (/mempool/mainnet/backend/node_modules/ws/lib/receiver.js:78:10)
    at writeOrBuffer (node:internal/streams/writable:382:12)
    at Receiver.Writable.write (node:internal/streams/writable:333:10)
    at Socket.socketOnData (/mempool/mainnet/backend/node_modules/ws/lib/websocket.js:872:35)
    at Socket.emit (node:events:327:20)
    at addChunk (node:internal/streams/readable:304:12)
    at readableAddChunk (node:internal/streams/readable:279:9)
    at Socket.Readable.push (node:internal/streams/readable:218:10)
Emitted 'error' event on WebSocket instance at:
    at Receiver.receiverOnError (/mempool/mainnet/backend/node_modules/ws/lib/websocket.js:777:13)
    at Receiver.emit (node:events:327:20)
    at emitErrorNT (node:internal/streams/destroy:194:8)
    at emitErrorCloseNT (node:internal/streams/destroy:159:3)
    at processTicksAndRejections (node:internal/process/task_queues:80:21) {
  [Symbol(status-code)]: 1002
} 
npm ERR! code 1
npm ERR! path /mempool/mainnet/backend
npm ERR! command failed
npm ERR! command sh -c node --max-old-space-size=4096 dist/index.js
```

Temporary band-aid fix committed in 12b3ecd07854708f084335cc966dd3d55e8a6d53

**Comment by softsimon** [comment]
Fixed in 12b3ecd
