### ISSUE TITLE
Crash when running with lnd

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#2256]
```
/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:128
                            err = new Error(decodedResponse.error.message || '');
                                  ^

Error: JSON integer out of range
    at /Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:128:35
    at Array.forEach (<anonymous>)
    at IncomingMessage.<anonymous> (/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:125:25)
    at IncomingMessage.emit (node:events:539:35)
    at endReadableNT (node:internal/streams/readable:1345:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: -1
}
```

**Comment by nymkappa** [comment]
Fixed in https://github.com/mempool/mempool/pull/2266
