### ISSUE TITLE
Scan for .topology files

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#2257]
I would request is to modify the topology script to save files with a certain file extension like .topology and then scan for *.topology files to avoid this crash:

```
Aug  5 07:36:00 [66497] DEBUG: <lightning> Reading /mempool/topology/setup.py
Aug  5 07:36:00 [66497] DEBUG: <lightning> Invalid topology file /mempool/topology/setup.py, cannot parse the content
Aug  5 07:36:00 [66497] DEBUG: <lightning> Reading /mempool/topology/requirements.txt
Aug  5 07:36:00 [66497] DEBUG: <lightning> Invalid topology file /mempool/topology/requirements.txt, cannot parse the content
Aug  5 07:36:00 [66497] DEBUG: <lightning> Reading /mempool/topology/pyproject.toml
/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:262
        if (!Array.isArray(graph.graphml.graph.node)) {
                                         ^

TypeError: Cannot read properties of undefined (reading 'graph')
    at LightningStatsImporter.parseFile (/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:262:42)
    at LightningStatsImporter.$importHistoricalLightningStats (/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:218:30)
    at async LightningStatsImporter.$run (/mempool/mainnet-lightning/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:21:9)

> mempool-backend@2.5.0-dev start-production
> node --max-old-space-size=4096 dist/index.js

```

_Originally posted by @wiz in https://github.com/mempool/mempool/pull/2244#pullrequestreview-1062972068_

**Comment by nymkappa** [comment]
Fixed in https://github.com/mempool/mempool/pull/2261
