### ISSUE TITLE
error building frontend

### ISSUE THREAD

**Issue by seth586** [mempool/mempool#24]
Trying to build on FreeBSD 11.2,

```
[error] Error: Job name "..getProjectMetadata" does not exist.
    at Observable._subscribe (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/@angular-devkit/core/src/experimental/jobs/simple-scheduler.js:350:23)
    at Observable._trySubscribe (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/Observable.js:30:22)
    at /root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:22:31
    at Object.subscribeToResult (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at SwitchMapSubscriber.notifyNext (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:86:26)
    at InnerSubscriber._next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/InnerSubscriber.js:28:21)
    at InnerSubscriber.Subscriber.next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
    at /root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeTo.js:17:28
    at Object.subscribeToResult (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/util/subscribeToResult.js:10:45)
    at SwitchMapSubscriber._innerSub (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:65:54)
    at SwitchMapSubscriber._next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/operators/switchMap.js:55:14)
    at SwitchMapSubscriber.Subscriber.next (/root/mempool.space/frontend/node_modules/@angular/cli/node_modules/rxjs/internal/Subscriber.js:66:18)
```

**Comment by wiz** [comment]
Can you confirm what versions of NodeJS you're running? This isn't an OS issue, and we actually run the production site on FreeBSD, so it should work fine. I'm guessing you're using a weird version of NodeJS or NPM that might be causing issues. I just run `pkg install nodejs npm` on FreeBSD and the site works fine for me using README install instructions.

**Comment by softsimon** [comment]
Closing due to inactivity.
