### ISSUE TITLE
Backend crash

### ISSUE THREAD

**Issue by nymkappa** [mempool/mempool#2487]
```
/Users/nymkappa/Documents/mempool/backend/node_modules/mysql2/promise.js:341
    const localErr = new Error();
                     ^

Error: Lock wait timeout exceeded; try restarting transaction
    at PromisePool.query (/Users/nymkappa/Documents/mempool/backend/node_modules/mysql2/promise.js:341:22)
    at DB.query (/Users/nymkappa/Documents/mempool/backend/dist/database.js:36:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async LightningStatsImporter.computeNetworkStats (/Users/nymkappa/Documents/mempool/backend/dist/tasks/lightning/sync-tasks/stats-importer.js:272:17)
    at async LightningStatsUpdater.$logStatsDaily (/Users/nymkappa/Documents/mempool/backend/dist/tasks/lightning/stats-updater.service.js:28:9)
    at async LightningStatsUpdater.$runTasks (/Users/nymkappa/Documents/mempool/backend/dist/tasks/lightning/stats-updater.service.js:18:9) {
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sql: "UPDATE nodes SET capacity = 1367391, channels = 8 WHERE public_key = '02775fa86a65cee7d22e27bdc9a8a963d58705246f29ec200b97102c8106b4f4b8'",
  sqlState: 'HY000',
  sqlMessage: 'Lock wait timeout exceeded; try restarting transaction'
}
```

Happened after closing the laptop lid. This indicates a missing try/catch logic? But I cannot reproduce easily.

**Comment by nymkappa** [comment]
```
/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:66
            var err = new Error('ETIMEDOUT');
                      ^

Error: ETIMEDOUT
    at Timeout._onTimeout (/Users/nymkappa/Documents/mempool/backend/dist/rpc-api/jsonrpc.js:66:23)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7) {
  code: 'ETIMEDOUT'
}
```

**Comment by nymkappa** [comment]
Did not see this for a while, closing
