### ISSUE TITLE
DB migrations is broken

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#2858]
Using config:
```
    "BLOCKS_SUMMARIES_INDEXING": true,
    "USE_SECOND_NODE_FOR_MINFEE": true,
    "TRANSACTION_INDEXING": true,
    "ADVANCED_GBT_AUDIT": true,
    "ADVANCED_GBT_MEMPOOL": false
```

Upgrade from 40 to 49 crashes after migrating:
```
> mempool-backend@2.5.0-dev start-production
> node --max-old-space-size=4096 dist/index.js

Dec 18 23:39:52 [47150] NOTICE: Starting Mempool Server... (04fec6c)
Dec 18 23:39:52 [47150] INFO: Restoring mempool and blocks data from disk cache
Dec 18 23:39:52 [47150] DEBUG: Mempool blocks calculated in 0.003 seconds
Dec 18 23:39:52 [47150] INFO: Database connection established.
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Running migrations
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Database engine version '10.5.16-MariaDB'
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Current state.schema_version 40
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Latest DatabaseMigration.version is 49
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE channels SET closing_reason = NULL WHERE closing_reason = 1
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 41 WHERE name = 'schema_version';
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD closing_resolved tinyint(1) DEFAULT 0
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 42 WHERE name = 'schema_version';
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
CREATE TABLE IF NOT EXISTS nodes_records (
      public_key varchar(66) NOT NULL,
      type int(10) unsigned NOT NULL,
      payload blob NOT NULL,
      UNIQUE KEY public_key_type (public_key, type),
      INDEX (public_key),
      FOREIGN KEY (public_key)
        REFERENCES nodes (public_key)
        ON DELETE CASCADE
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 43 WHERE name = 'schema_version';
Dec 18 23:39:52 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE blocks_summaries SET template = NULL
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 44 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `blocks_audits` ADD fresh_txs JSON DEFAULT "[]"
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 45 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE blocks MODIFY blockTimestamp timestamp NOT NULL DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 46 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `blocks` ADD cpfp_indexed tinyint(1) DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
CREATE TABLE IF NOT EXISTS cpfp_clusters (
      root varchar(65) NOT NULL,
      height int(10) NOT NULL,
      txs JSON DEFAULT NULL,
      fee_rate double unsigned NOT NULL,
      PRIMARY KEY (root)
    ) ENGINE=InnoDB DEFAULT CHARSET=utf8;
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 47 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD source_checked tinyint(1) DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD closing_fee bigint(20) unsigned DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD node1_funding_balance bigint(20) unsigned DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD node2_funding_balance bigint(20) unsigned DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD node1_closing_balance bigint(20) unsigned DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD node2_closing_balance bigint(20) unsigned DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD funding_ratio float unsigned DEFAULT NULL
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD closed_by varchar(66) DEFAULT NULL
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD single_funded tinyint(1) DEFAULT 0
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
ALTER TABLE `channels` ADD outputs JSON DEFAULT "[]"
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 48 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
TRUNCATE TABLE `blocks_audits`
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 49 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] NOTICE: MIGRATIONS: Upgrading database schema version number to 49
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
START TRANSACTION;
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
UPDATE state SET number = 49 WHERE name = 'schema_version';
Dec 19 00:00:29 [47150] DEBUG: MIGRATIONS: Execute query:
COMMIT;
Dec 19 00:00:29 [47150] NOTICE: MIGRATIONS: OK. Database schema have been migrated from version 40 to 49 (latest version)
Dec 19 00:00:29 [47150] INFO: Starting statistics service
Dec 19 00:00:29 [47150] INFO: Starting currency rates service
Dec 19 00:00:29 [47150] INFO: Currency rates service will be queried over clearnet using https://price.bisq.wiz.biz/getAllMarketPrices
Dec 19 00:00:29 [47150] DEBUG: Querying currency rates service...
Dec 19 00:00:29 [47150] NOTICE: Mempool Server is running on port 8999
Dec 19 00:00:29 [47150] INFO: Updating latest mining pools from https://raw.githubusercontent.com/mempool/mining-pools/master/pools.json over clearnet
Dec 19 00:00:30 [47150] DEBUG: USD Conversion Rate: 16759.35
Dec 19 00:00:30 [47150] DEBUG: Pools.json sha | Current: d71cdbd05a8f34113f62fad2f2def0134b1cacac | Github: d71cdbd05a8f34113f62fad2f2def0134b1cacac
Dec 19 00:00:30 [47150] DEBUG: Initial difficulty adjustment data set.
Dec 19 00:00:30 [47150] DEBUG: New block found (#767999)!
Dec 19 00:00:30 [47150] DEBUG: Indexing tx 1 of 887 in block #767999
Dec 19 00:00:30 [47150] DEBUG: Indexing tx 90 of 887 in block #767999
Dec 19 00:00:31 [47150] DEBUG: Indexing tx 179 of 887 in block #767999
Dec 19 00:00:31 [47150] DEBUG: Indexing tx 268 of 887 in block #767999
Dec 19 00:00:31 [47150] DEBUG: Indexing tx 446 of 887 in block #767999
Dec 19 00:00:32 [47150] DEBUG: Indexing tx 535 of 887 in block #767999
Dec 19 00:00:32 [47150] DEBUG: Indexing tx 624 of 887 in block #767999
Dec 19 00:00:32 [47150] DEBUG: Indexing tx 713 of 887 in block #767999
Dec 19 00:00:32 [47150] DEBUG: Indexing tx 802 of 887 in block #767999
Dec 19 00:00:32 [47150] DEBUG: 150 of 887 found in mempool. 737 fetched through backend service.
Dec 19 00:00:32 [47150] INFO: Cannot save block price for 767999 because the price updater hasnt completed yet. Trying again in 10 seconds.
Dec 19 00:00:32 [47150] DEBUG: Mempool templates calculated in 0.007 seconds
Dec 19 00:00:32 [47150] DEBUG: Mempool blocks calculated in 0 seconds
Dec 19 00:00:33 [47150] DEBUG: New block found (#768000)!
Dec 19 00:00:33 [47150] ERR: Cannot save transaction cpfp cluster into db. Reason: Unknown column 'cluster' in 'field list'
/mempool/mainnet/backend/node_modules/mysql2/promise.js:341
    const localErr = new Error();
                     ^

Error: Unknown column 'cluster' in 'field list'
    at PromisePool.query (/mempool/mainnet/backend/node_modules/mysql2/promise.js:341:22)
    at DB.query (/mempool/mainnet/backend/dist/database.js:36:21)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async TransactionRepository.$setCluster (/mempool/mainnet/backend/dist/repositories/TransactionRepository.js:11:13)
    at async Blocks.$indexCPFP (/mempool/mainnet/backend/dist/api/blocks.js:707:25) {
  code: 'ER_BAD_FIELD_ERROR',
  errno: 1054,
  sql: '\n' +
    '          INSERT INTO transactions\n' +
    '          (\n' +
    '            txid,\n' +
    '            cluster\n' +
    '          )\n' +
    "          VALUE ('252bdfb4b859c65254681415851d45a40e83e42539cb4fb519704ff8074b3cbc', '252bdfb4b859c65254681415851d45a40e83e42539cb4fb519704ff8074b3cbc')\n" +
    '          ON DUPLICATE KEY UPDATE\n' +
    "            cluster = '252bdfb4b859c65254681415851d45a40e83e42539cb4fb519704ff8074b3cbc'\n" +
    '        ;',
  sqlState: '42S22',
  sqlMessage: "Unknown column 'cluster' in 'field list'"
}
```

**Comment by wiz** [comment]
Also, why does it crash on mainnet, but signet handles the exception and keeps going?

**Comment by mononaut** [comment]
Looks like the `transactions` table creation is getting skipped
https://github.com/mempool/mempool/blob/343a48818b9057b7fd0b428fef1e46205acca8c8/backend/src/api/database-migration.ts#L420-L425
https://github.com/mempool/mempool/blob/343a48818b9057b7fd0b428fef1e46205acca8c8/backend/src/api/database-migration.ts#L907-L914
does that table already exist in your mainnet db with a different schema?

**Comment by wiz** [comment]
```
root@localhost [mempool]> describe transactions;
+-------------+-------------+------+-----+---------+-------+
| Field       | Type        | Null | Key | Default | Extra |
+-------------+-------------+------+-----+---------+-------+
| blockheight | int(11)     | NO   | MUL | NULL    |       |
| txid        | varchar(65) | NO   | PRI | NULL    |       |
| fee         | double      | NO   |     | NULL    |       |
| feePerVsize | double      | NO   |     | NULL    |       |
+-------------+-------------+------+-----+---------+-------+
4 rows in set (0.001 sec)

root@localhost [mempool]> select count(*) from transactions;
+----------+
| count(*) |
+----------+
|    61439 |
+----------+
1 row in set (0.170 sec)
```

**Comment by wiz** [comment]
@softsimon I'm guessing this is super old legacy stuff in our prod db?

**Comment by wiz** [comment]
I'm guessing this `transactions` table was in our production database because we used it around block height 618665 when @softsimon and I were first working on the full explorer functionality in the early days

**Comment by mononaut** [comment]
cool, should I add a `DROP TABLE` to the 46 -> 47 migration to clear that out?

**Comment by wiz** [comment]
ok it didn't reproduce on a different server so guess this is a non-issue... and if it's only on a few old servers then I can just drop it manually before upgrading.... thanks tho 😅
