### ISSUE TITLE
crash due to handleNewBlock undefined reading 'weight'

### ISSUE THREAD

**Issue by wiz** [mempool/mempool#3558]
```
Mar 23 09:05:06 [93895] DEBUG: [Mining] Indexed 0 difficulty adjustments
Mar 23 09:05:07 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:07 [93895] DEBUG: Mempool updated in 1.282 seconds. New size: 52838 (+7)
Mar 23 09:05:07 [93895] DEBUG: Mempool templates calculated in 0.468 seconds
Mar 23 09:05:08 [93895] DEBUG: Updating mempool...
Mar 23 09:05:09 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:09 [93895] DEBUG: Mempool updated in 0.981 seconds. New size: 52856 (+18)
Mar 23 09:05:09 [93895] DEBUG: Mempool templates calculated in 0.861 seconds
Mar 23 09:05:10 [93895] DEBUG: Updating mempool...
Mar 23 09:05:10 [93895] DEBUG: [Mining] Indexing daily network hashrate
Mar 23 09:05:10 [93895] DEBUG: [Mining] Daily network hashrate indexing completed: indexed 0 days
Mar 23 09:05:12 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:12 [93895] DEBUG: Mempool updated in 1.254 seconds. New size: 52868 (+12)
Mar 23 09:05:11 [93895] DEBUG: Mempool templates calculated in 0.584 seconds
Mar 23 09:05:13 [93895] DEBUG: Updating mempool...
Mar 23 09:05:14 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:14 [93895] DEBUG: Mempool updated in 1.202 seconds. New size: 52881 (+13)
Mar 23 09:05:14 [93895] DEBUG: Mempool templates calculated in 0.746 seconds
Mar 23 09:05:15 [93895] DEBUG: Updating mempool...
Mar 23 09:05:15 [93895] DEBUG: [Mining] Indexing weekly mining pool hashrate
Mar 23 09:05:15 [93895] DEBUG: [Mining] Weekly mining pools hashrates indexing completed: indexed 0 weeks
Mar 23 09:05:16 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:16 [93895] DEBUG: Mempool updated in 1.499 seconds. New size: 52885 (+4)
Mar 23 09:05:16 [93895] DEBUG: Mempool templates calculated in 0.458 seconds
Mar 23 09:05:17 [93895] DEBUG: Updating mempool...
Mar 23 09:05:18 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:18 [93895] DEBUG: Mempool updated in 1.102 seconds. New size: 52897 (+12)
Mar 23 09:05:19 [93895] DEBUG: Mempool templates calculated in 1.036 seconds
Mar 23 09:05:20 [93895] DEBUG: Updating mempool...
Mar 23 09:05:23 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:23 [93895] DEBUG: Mempool updated in 3.306 seconds. New size: 52903 (+6)
Mar 23 09:05:25 [93895] DEBUG: [Mining] Blocks summaries indexing completed: indexed 0 blocks
Mar 23 09:05:25 [93895] DEBUG: Memory usage: 3.93 GB / 16.05 GB
Mar 23 09:05:23 [93895] DEBUG: Mempool templates calculated in 0.54 seconds
Mar 23 09:05:25 [93895] DEBUG: Updating mempool...
Mar 23 09:05:26 [93895] ERR: updateBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:26 [93895] DEBUG: Mempool updated in 0.81 seconds. New size: 52924 (+21)
Mar 23 09:05:26 [93895] DEBUG: Mempool templates calculated in 1.002 seconds
Mar 23 09:05:27 [93895] DEBUG: New block found (#782105)!
Mar 23 09:05:27 [93895] DEBUG: Updated orphaned blocks cache. Found 4 orphaned blocks
Mar 23 09:05:27 [93895] DEBUG: Indexing tx 1 of 478 in block #782105
Mar 23 09:05:27 [93895] DEBUG: 477 of 478 found in mempool. 1 fetched through backend service.
Mar 23 09:05:29 [93895] ERR: makeBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
Mar 23 09:05:29 [93895] ERR: makeBlockTemplates failed. Cannot read properties of undefined (reading 'fee')
/mempool/mainnet/backend/dist/api/audit.js:41
                displacedWeight += mempool[txid].weight;
                                                 ^

TypeError: Cannot read properties of undefined (reading 'weight')
    at Audit.auditBlock (/mempool/mainnet/backend/dist/api/audit.js:41:50)
    at WebsocketHandler.handleNewBlock (/mempool/mainnet/backend/dist/api/websocket-handler.js:426:87)

> mempool-backend@2.5.0-dev start-production
> node --max-old-space-size=16384 dist/index.js

```

**Comment by softsimon** [comment]
Should be related to https://github.com/mempool/mempool/issues/3453
