### ISSUE TITLE
Cannot get fetch orphaned blocks. Reason: ETIMEDOUT

### ISSUE THREAD

**Issue by nailiujac** [mempool/mempool#4310]
### Description

With the installation of Docker, upon starting it with docker-compose,  it fails to synchronize completely. 

![image](https://github.com/mempool/mempool/assets/83184419/b2add441-8cd5-4bd9-b028-46d819af268b)

#### Version
https://github.com/mempool/mempool/commit/7c09dd1b70cf8b777b9ea1b4f03e79398a596079

### Steps to reproduce

Run with docker-compose

### Expected behaviour

Complete synchronization

### Actual behaviour

Gest this error:

```
docker-api-1  | Oct  9 19:57:06 [121] ERR: Cannot get fetch orphaned blocks. Reason: ETIMEDOUT
docker-api-1  | Oct  9 19:57:06 [121] NOTICE: Mempool Server is running on port 8999
docker-api-1  | Oct  9 20:01:11 [121] WARN: Exception in runMainUpdateLoop(). Retrying in 10 sec. Reason: ETIMEDOUT. Stack trace: Error: ETIMEDOUT
docker-api-1  |     at Timeout._onTimeout (/backend/package/rpc-api/jsonrpc.js:66:23)
docker-api-1  |     at listOnTimeout (node:internal/timers:559:17)
docker-api-1  |     at processTimers (node:internal/timers:502:7)
docker-api-1  | Oct  9 20:03:21 [121] WARN: Exception in runMainUpdateLoop(). Retrying in 20 sec. Reason: ETIMEDOUT. Stack trace: Error: ETIMEDOUT
docker-api-1  |     at Timeout._onTimeout (/backend/package/rpc-api/jsonrpc.js:66:23)
docker-api-1  |     at listOnTimeout (node:internal/timers:559:17)
docker-api-1  |     at processTimers (node:internal/timers:502:7)
docker-api-1  | Oct  9 20:05:41 [121] WARN: Exception in runMainUpdateLoop(). Retrying in 40 sec. Reason: ETIMEDOUT. Stack trace: Error: ETIMEDOUT
docker-api-1  |     at Timeout._onTimeout (/backend/package/rpc-api/jsonrpc.js:66:23)
docker-api-1  |     at listOnTimeout (node:internal/timers:559:17)
docker-api-1  |     at processTimers (node:internal/timers:502:7)
docker-api-1  | Oct  9 20:08:21 [121] WARN: Exception in runMainUpdateLoop(). Retrying in 60 sec. Reason: ETIMEDOUT. Stack trace: Error: ETIMEDOUT
docker-api-1  |     at Timeout._onTimeout (/backend/package/rpc-api/jsonrpc.js:66:23)
docker-api-1  |     at listOnTimeout (node:internal/timers:559:17)
docker-api-1  |     at processTimers (node:internal/timers:502:7)
```

#### Device or machine

- Ubuntu server.
- Bitcoin core and Falcrum

**Comment by nymkappa** [comment]
It's an issue with your setup. Your nodejs backend probably cannot access your bitcoin core RPC.

**Comment by nailiujac** [comment]
I think I know what's going on. The 403 error only occurs when invoking some endpoints (for example, coinbase and bitfinex). I've reproduce it using the `curl` command, and I get the same result. To resolve it, I have to pass the `--cookie` option. For example:

```
curl -v --cookie --socks5 127.0.0.1:9050 https://api.exchange.coinbase.com/products/BTC-USD/candles?granularity=3600
```

According to the documentation for this option of the command:

> This option also activates the cookie engine which makes curl record incoming cookies, which may be handy if you are using this in combination with the -L, --location option or do multiple URL transfers on the same invoke.

To solve this, I suppose it would be sufficient to use the corresponding parameterization in Axios.
