### ISSUE TITLE
vin.scriptsig_asm might be undefined with Core only

### ISSUE THREAD

**Issue by softsimon** [mempool/mempool#5150]
We got the report that the backend threw 500  undefined (reading 'split') ..  I was not able to reproduce that, but the frontend was. So it should be related. Basically **scriptsig_asm** can be undefined.

```
TypeError: Cannot read properties of undefined (reading 'split')
    at calcSegwitFeeGains (bitcoin.utils.ts:26:50)
    at TxFeaturesComponent.ngOnChanges (tx-features.component.ts:40:42)

```

**Comment by tchjntr** [comment]
Here are the "undefined" related errors/messages I've been able to spot so far:

**500: Internal Server Error** - frontend when viewing a transaction (it happens very often but it's not reproducible in a consistent way)

![mempool_error_500](https://github.com/mempool/mempool/assets/152696739/881d1ac4-1f1e-4f2f-8be8-8207dd096137)

**Cannot read properties of undefined (reading 'split')** - API endpoint when checking the same transaction as above (it happens very often but it's not reproducible in a consistent way)

![mempool_readingsplit](https://github.com/mempool/mempool/assets/152696739/3e17c5c2-e378-4af3-a73e-16c0ae83eb82)

**WARN: Failed to parse mempoool and blocks cache. Skipping. Reason: Cannot read properties of undefined (reading 'split')** - this warning pops up every time I restart the mempool service

![Screenshot 2024-06-13 at 13 43 29](https://github.com/mempool/mempool/assets/152696739/28044e3a-148d-486f-b282-e70ba3996a9c)

**Error loading address data. (undefined: undefined)** - This error message is visible every time I try to check P2PK addresses. I've got this message consistently with both electrs and Fulcrum as Electrum backend.

![mempool_p2pk](https://github.com/mempool/mempool/assets/152696739/73a1a66a-f4ee-4480-9cf8-f353bab62716)

**Comment by tchjntr** [comment]
![screenshot-192 168 178 21_4081-2024 06](https://github.com/mempool/mempool/assets/152696739/284726ee-8a82-44ae-9fb9-db3499dc44c6)

![Screenshot 2024-06-15 at 14 19 59](https://github.com/mempool/mempool/assets/152696739/ae173743-fe5d-4eee-b6d1-e7b798ae239d)

There's no issue loading that address on [mempool.space](https://mempool.space/address/bc1qssleem6wv069c7saamfegssgreay8dqpwuhalmsr5ruj6hp9rn7s3kshg7).

**Comment by tchjntr** [comment]
Spotted these in the log:

```
Jun 18 15:10:47 u59pro node[658189]: Jun 18 15:10:47 [658189] WARN: [Mining] Chain divergence detected at block 848477, re-indexing most recent data
Jun 18 15:10:47 u59pro node[658189]: Jun 18 15:10:47 [658189] INFO: [Mining] Delete newer blocks from height 848467 from the database
Jun 18 15:10:47 u59pro node[658189]: Jun 18 15:10:47 [658189] INFO: [Mining] Delete latest hashrates data points from the database
Jun 18 15:10:47 u59pro node[658189]: Jun 18 15:10:47 [658189] DEBUG: Memory usage: 2.91 GB / 8.05 GB
Jun 18 15:10:47 u59pro node[658189]: Jun 18 15:10:47 [658189] INFO: Delete newer cpfp clusters from height 848467 from the database
Jun 18 15:11:32 u59pro node[658189]: Jun 18 15:11:32 [658189] INFO: Delete newer accelerations from height 848467 from the database
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
Jun 18 15:11:33 u59pro node[658189]: Jun 18 15:11:33 [658189] WARN: Failed to classify transaction: Cannot read properties of undefined (reading 'length')
```

**Comment by tchjntr** [comment]
Just spotted another "undefined" error message:

`[1638841] ERR: RUST updateBlockTemplates failed. Cannot read properties of undefined (reading 'vsize')`
