### ISSUE TITLE
SyntaxError: Unexpected token '.' and Error: Cannot find module 'node:crypto'

### ISSUE THREAD

**Issue by VegArchie** [mempool/mempool#5152]
### Description
When trying to run `npm run start` after a new install, I get hundreds of errors related to "?" appearing in the code. There are a few extra "." as well. Even when clearing them, I ultimately get an error related to "Error: Cannot find module 'node:crypto'"

It seems like npm is messing up the build and adding the "?" and there is no more support for npm crypto. 

### Steps to reproduce
following instructions for backend install, errors occur after running  `npm run start`

### Expected behaviour
Should start backend

### Actual behaviour
Failure do to errors.

#### Device or machine
Linux Ubuntu - Zorin 17

#### Additional info
`Error: Cannot find module 'node:crypto'
Require stack:
- /home/bitcoin/mempool/backend/node_modules/@noble/hashes/cryptoNode.js
- /home/bitcoin/mempool/backend/node_modules/@noble/hashes/utils.js
- /home/bitcoin/mempool/backend/node_modules/@noble/hashes/_sha2.js
- /home/bitcoin/mempool/backend/node_modules/@noble/hashes/ripemd160.js
- /home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/crypto.js
- /home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/payments/p2pkh.js
- /home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/payments/index.js
- /home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/address.js
- /home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/index.js
- /home/bitcoin/mempool/backend/dist/api/common.js
- /home/bitcoin/mempool/backend/dist/api/bitcoin/esplora-api.js
- /home/bitcoin/mempool/backend/dist/api/bitcoin/bitcoin-api-factory.js
- /home/bitcoin/mempool/backend/dist/index.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/bitcoin/mempool/backend/node_modules/@noble/hashes/cryptoNode.js:4:12)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/bitcoin/mempool/backend/node_modules/@noble/hashes/cryptoNode.js',
    '/home/bitcoin/mempool/backend/node_modules/@noble/hashes/utils.js',
    '/home/bitcoin/mempool/backend/node_modules/@noble/hashes/_sha2.js',
    '/home/bitcoin/mempool/backend/node_modules/@noble/hashes/ripemd160.js',
    '/home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/crypto.js',
    '/home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/payments/p2pkh.js',
    '/home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/payments/index.js',
    '/home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/address.js',
    '/home/bitcoin/mempool/backend/node_modules/bitcoinjs-lib/src/index.js',
    '/home/bitcoin/mempool/backend/dist/api/common.js',
    '/home/bitcoin/mempool/backend/dist/api/bitcoin/esplora-api.js',
    '/home/bitcoin/mempool/backend/dist/api/bitcoin/bitcoin-api-factory.js',
    '/home/bitcoin/mempool/backend/dist/index.js'
  ]
}
`

**Comment by VegArchie** [comment]
I tried using npm version 7.0.15 and I am having the same errors.
