### ISSUE TITLE
Error starting backend

### ISSUE THREAD

**Issue by gustavonalle** [mempool/mempool#72]
``` 
May 14 08:38:53 endor node[3814107]:       ...options
May 14 08:38:53 endor node[3814107]:       ^^^
May 14 08:38:53 endor node[3814107]: SyntaxError: Unexpected token ...
May 14 08:38:53 endor node[3814107]:     at createScript (vm.js:74:10)
May 14 08:38:53 endor node[3814107]:     at Object.runInThisContext (vm.js:116:10)
May 14 08:38:53 endor node[3814107]:     at Module._compile (module.js:533:28)
May 14 08:38:53 endor node[3814107]:     at Object.Module._extensions..js (module.js:580:10)
May 14 08:38:53 endor node[3814107]:     at Module.load (module.js:503:32)
May 14 08:38:53 endor node[3814107]:     at tryModuleLoad (module.js:466:12)
May 14 08:38:53 endor node[3814107]:     at Function.Module._load (module.js:458:3)
May 14 08:38:53 endor node[3814107]:     at Module.require (module.js:513:17)
May 14 08:38:53 endor node[3814107]:     at require (internal/module.js:11:18)
May 14 08:38:53 endor node[3814107]:     at Object.<anonymous> (/home/mempool.space/backend/node_modules/ws/index.js:3:19)
```

Do I need a specific version of node or npm? It was working fine with mempool.space before the last release with: 

```
$ npm -version; node --version
6.14.4
v12.16.3
```

**Comment by gustavonalle** [comment]
Apparently I was using node ```v8.2.1``` in the system service, not the version I was thinking. I will upgrade it
