### ISSUE TITLE
Avoiding Electrs?

### ISSUE THREAD

**Issue by gustavonalle** [mempool/mempool#73]
Does mempool requires blockstream electrs (Blockstream's fork of electrs)? Is it possible to avoid it, since it is a massively bloated index that wastes hundreds of GBs of disk space?

I got error:
```
Updating mempool
getRawMempool error. Error: Invalid URI "undefined/mempool/txids"
    at Request.init (/home/mempool.space/backend/node_modules/request/request.js:273:31)
    at new Request (/home/mempool.space/backend/node_modules/request/request.js:127:8)
    at request (/home/mempool.space/backend/node_modules/request/index.js:53:10)
    at /home/mempool.space/backend/dist/api/bitcoin/electrs-api.js:32:13
    at new Promise (<anonymous>)
    at ElectrsApi.getRawMempool (/home/mempool.space/backend/dist/api/bitcoin/electrs-api.js:31:16)
    at Mempool.<anonymous> (/home/mempool.space/backend/dist/api/mempool.js:94:66)
    at Generator.next (<anonymous>)
    at /home/mempool.space/backend/dist/api/mempool.js:8:71
    at new Promise (<anonymous>)
```

When using this config:

```json
{
  "ENV": "dev",
  "DB_HOST": "localhost",
  "DB_PORT": 3306,
  "DB_USER": "ddddd",
  "DB_PASSWORD": "ddddd",
  "DB_DATABASE": "mempool",
  "HTTP_PORT": 3000,
  "API_ENDPOINT": "/api/v1/",
  "CHAT_SSL_ENABLED": false,
  "MEMPOOL_REFRESH_RATE_MS": 500,
  "INITIAL_BLOCK_AMOUNT": 8,
  "DEFAULT_PROJECTED_BLOCKS_AMOUNT": 3,
  "KEEP_BLOCK_AMOUNT": 24,
  "BITCOIN_NODE_HOST": "localhost",
  "BITCOIN_NODE_PORT": 8332,
  "BITCOIN_NODE_USER": "ddddd",
  "BITCOIN_NODE_PASS": "ddddd",
  "TX_PER_SECOND_SPAN_SECONDS": 150
}
```

**Comment by softsimon** [comment]
V2 is electrs only. v1 is still bitcoind only, but with limited features.

**Comment by gustavonalle** [comment]
Right, so I assume ```master``` is what will become v2, I will revert to the tag.
BTW, given the massive resource hog that is blockstream electrs (it rivals the Bitcoin blockchain itself!), probably you want to reconsider making it mandatory?  :smile:
